theme: jekyll-theme-midnight
title: Nick Nonnenmacher's Portfolio as helped make from Borat subsequent movie film as example of my insane STEM skills
description: Collection of Open Source GIS project work during Spring 2021
